@startuml
abstract class Personaje {
    - vida: int
    - experiencia: int
    - batallasGanadas: int
    - nombre: String
    + Personaje(vida: int, nombre: String)
    + <<abstract>> atacar(enemigo: Personaje): void
    + <<abstract>> defensa(): int
    + toString(): String
}

class Guerrero {
    - habilidad: String
    + Guerrero(vida: int, nombre: String, habilidad: String)
    + atacar(enemigo: Personaje): void
    + defensa(): int
    + toString(): String
}

class Mago {
    - estrategia: String
    + Mago(vida: int, nombre: String, estrategia: String)
    + atacar(enemigo: Personaje): void
    + defensa(): int
    + toString(): String
}

class Arquero {
    - atributos: String
    + Arquero(vida: int, nombre: String, atributos: String)
    + atacar(enemigo: Personaje): void
    + defensa(): int
    + toString(): String
}

class P1JuegoRolEjecutor {
    + main(args: String[]): void
}

Personaje <|-- Guerrero
Personaje <|-- Mago
Personaje <|-- Arquero
P1JuegoRolEjecutor ... Personaje
@enduml